### ISSUE TITLE
[SOLVED] 504 for URL http://api.flickr.com/services/upload/

### ISSUE THREAD

**Issue by freeman59** [syno2flickr/syno2flickr#1]
Bonjour

J'ai un petit probleme depuis hier soir avec Syno2Flickr, l'upload s'est arrêté en cours de route, ce matin quand je le relance, j'ai un message à chaque transfert de photos :

Processing: |==================================================|  99% (9.9MB/9.9MB)java.lang.NullPointerException
    at org.jickr.Request.postAndGetResponse(Request.java:430)
    at org.jickr.Photo.uploadNewPhoto(Photo.java:353)
    at ch.jachen.dev.flickr.Syno2Flickr.main(Syno2Flickr.java:417)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

An error occured while uploading file /volume1/public/Syno2Flickr/SD-4572.jpg
IO Error: Server returned HTTP response code: 504 for URL: http://api.flickr.com/services/upload/

Une idée du probleme ??

**Comment by koensegers** [comment]
Mine is similar. Also since yesterday (depuis hier)

Sending IMG_0069.JPG (1/1)
Processing: |==================================================||  99% (1.8MB/1.8MB)java.lang.NullPointerException
        at org.jickr.Request.postAndGetResponse(Request.java:430)
        at org.jickr.Photo.uploadNewPhoto(Photo.java:353)
        at ch.jachen.dev.flickr.Syno2Flickr.main(Syno2Flickr.java:417)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

An error occured while uploading file /volume1/Syno2Flickr/AutoUpload/IMG_0069.JPG
IO Error: Server returned HTTP response code: 411 for URL: http://api.flickr.com/services/upload/

Any idea?

**Comment by syno2flickr** [comment]
Ok I will check this week end. Thanks for your feedbacks.

**Comment by syno2flickr** [comment]
@koensegers I could reproduce HTTP error 411 and I posted a new version (0.1.2). 

@freeman59 J'ai par contre pas réussi à reproduire l'erreur 504... essaies la nouvelle version, et redis-moi si ça marche pas.
